// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/cadence/service/history/queuev2 (interfaces: CachedQueueReader)
//
// Generated by this command:
//
//	mockgen -package queuev2 -destination queue_reader_cached_mock.go github.com/uber/cadence/service/history/queuev2 CachedQueueReader
//

// Package queuev2 is a generated GoMock package.
package queuev2

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	persistence "github.com/uber/cadence/common/persistence"
)

// MockCachedQueueReader is a mock of CachedQueueReader interface.
type MockCachedQueueReader struct {
	ctrl     *gomock.Controller
	recorder *MockCachedQueueReaderMockRecorder
	isgomock struct{}
}

// MockCachedQueueReaderMockRecorder is the mock recorder for MockCachedQueueReader.
type MockCachedQueueReaderMockRecorder struct {
	mock *MockCachedQueueReader
}

// NewMockCachedQueueReader creates a new mock instance.
func NewMockCachedQueueReader(ctrl *gomock.Controller) *MockCachedQueueReader {
	mock := &MockCachedQueueReader{ctrl: ctrl}
	mock.recorder = &MockCachedQueueReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCachedQueueReader) EXPECT() *MockCachedQueueReaderMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockCachedQueueReader) Clear() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Clear")
}

// Clear indicates an expected call of Clear.
func (mr *MockCachedQueueReaderMockRecorder) Clear() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockCachedQueueReader)(nil).Clear))
}

// GetTask mocks base method.
func (m *MockCachedQueueReader) GetTask(arg0 context.Context, arg1 *GetTaskRequest) (*GetTaskResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", arg0, arg1)
	ret0, _ := ret[0].(*GetTaskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockCachedQueueReaderMockRecorder) GetTask(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockCachedQueueReader)(nil).GetTask), arg0, arg1)
}

// Inject mocks base method.
func (m *MockCachedQueueReader) Inject(tasks []persistence.Task) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Inject", tasks)
}

// Inject indicates an expected call of Inject.
func (mr *MockCachedQueueReaderMockRecorder) Inject(tasks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inject", reflect.TypeOf((*MockCachedQueueReader)(nil).Inject), tasks)
}

// LookAHead mocks base method.
func (m *MockCachedQueueReader) LookAHead(ctx context.Context, req *LookAHeadRequest) (*LookAHeadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookAHead", ctx, req)
	ret0, _ := ret[0].(*LookAHeadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookAHead indicates an expected call of LookAHead.
func (mr *MockCachedQueueReaderMockRecorder) LookAHead(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookAHead", reflect.TypeOf((*MockCachedQueueReader)(nil).LookAHead), ctx, req)
}

// Start mocks base method.
func (m *MockCachedQueueReader) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockCachedQueueReaderMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockCachedQueueReader)(nil).Start))
}

// Stop mocks base method.
func (m *MockCachedQueueReader) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockCachedQueueReaderMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockCachedQueueReader)(nil).Stop))
}

// UpdateReadLevel mocks base method.
func (m *MockCachedQueueReader) UpdateReadLevel(readLevel persistence.HistoryTaskKey) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateReadLevel", readLevel)
}

// UpdateReadLevel indicates an expected call of UpdateReadLevel.
func (mr *MockCachedQueueReaderMockRecorder) UpdateReadLevel(readLevel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReadLevel", reflect.TypeOf((*MockCachedQueueReader)(nil).UpdateReadLevel), readLevel)
}
